# Generated by Django 5.2.1 on 2025-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_user_initiated',
            field=models.BooleanField(db_index=True, default=False, help_text='True, если эта статья была добавлена пользователем напрямую, а не как связанная ссылка.', verbose_name='Добавлено пользователем напрямую'),
        ),
    ]
