# Generated by Django 5.2.1 on 2025-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_article_is_user_initiated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(related_name='authors', to='papers.article', verbose_name='Articles'),
        ),
    ]
