# Generated by Django 5.2.1 on 2025-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_remove_article_authors_author_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', through='papers.ArticleAuthorOrder', to='papers.author', verbose_name='Авторы'),
        ),
    ]
