# Generated by Django 5.2.1 on 2025-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_remove_author_articles_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='structured_content',
            field=models.JSONField(blank=True, help_text='Содержимое статьи, разбитое по секциям (например, abstract, introduction, methods, results, discussion, conclusion)', null=True, verbose_name='Структурированное содержимое'),
        ),
    ]
