# Generated by Django 5.2.1 on 2025-06-05 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_alter_article_structured_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(blank=True, help_text='Например, introduction, methods, или заголовок пользовательской секции.', max_length=255, null=True, verbose_name='Ключ/заголовок секции')),
                ('segment_text', models.TextField(help_text='Выделенный пользователем или автоматически извлеченный фрагмент текста.', verbose_name='Текст сегмента')),
                ('inline_citation_markers', models.JSONField(blank=True, default=list, help_text="Список текстовых маркеров цитирования, найденных в сегменте, например, ['[1]', '(Smith 2023)']", null=True, verbose_name='Маркеры инлайн-цитат')),
                ('llm_analysis_notes', models.TextField(blank=True, null=True, verbose_name='Заметки анализа LLM')),
                ('llm_veracity_score', models.FloatField(blank=True, null=True, verbose_name='Оценка достоверности LLM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_segments', to='papers.article', verbose_name='Целевая статья')),
                ('cited_references', models.ManyToManyField(blank=True, related_name='supporting_segments', to='papers.referencelink', verbose_name='Цитируемые/связанные ссылки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший/изменивший сегмент')),
            ],
            options={
                'verbose_name': 'Анализируемый сегмент текста',
                'verbose_name_plural': 'Анализируемые сегменты текста',
                'ordering': ['article', 'created_at'],
            },
        ),
    ]
