# Generated by Django 5.2.1 on 2025-06-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_analyzedsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedsegment',
            name='llm_model_name',
            field=models.CharField(blank=True, help_text="Например: 'gpt-4o-mini'", max_length=100, null=True, verbose_name='Название LLM модели'),
        ),
    ]
