# Generated by Django 5.2.1 on 2025-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_analyzedsegment_llm_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedsegment',
            name='prompt_used',
            field=models.TextField(blank=True, null=True, verbose_name='Использованный промпт'),
        ),
    ]
