# Generated by Django 5.2.1 on 2025-06-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_analyzedsegment_prompt_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencelink',
            options={'ordering': ['order'], 'verbose_name': 'Библиографическая ссылка', 'verbose_name_plural': 'Библиографические ссылки'},
        ),
        migrations.AddField(
            model_name='referencelink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
