# Generated by Django 5.2.1 on 2025-06-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_alter_referencelink_options_referencelink_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pmc_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='PubMed Central (PMC) ID'),
        ),
    ]
