# Generated by Django 5.2.1 on 2025-06-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_article_pmc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='articles_pdf/', verbose_name='PDF файл'),
        ),
    ]
