# Generated by Django 5.2.1 on 2025-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0012_article_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_text',
            field=models.TextField(blank=True, help_text='Текстовое содержимое pdf файла полученное из MarkItDown, MarkerPDF или др.', null=True, verbose_name='Текст из PDF'),
        ),
    ]
