# docker-compose -f docker-compose.yml up -d
# docker-compose -f docker-compose.yml down -v
# подключиться к контейнеру созданной бд можно командой:
# docker exec -it scraping_postgres psql --username=scraping --dbname=scraping
# данные контейнеров храняться в папке ./tmp 


version: "3.8"

services:

  postgres:
    image: postgres:14-alpine
    container_name: article_postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - article-network
    environment:
      POSTGRES_PASSWORD: article
      POSTGRES_USER: article
      POSTGRES_DB: article
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: article_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: article@mail.com
      PGADMIN_DEFAULT_PASSWORD: article
    user: $UID:$GID
    volumes:
      - ./tmp/pgadmin-data:/var/lib/pgadmin:U
    depends_on:
      - postgres
    networks:
      - article-network

  redis:
    image: redis:latest
    container_name: article_redis
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - article-network
    volumes:
      - ./tmp/redis:/var/lib/redis
      - ./tmp/redis-config:/usr/local/etc/redis/redis.conf

networks:
  article-network:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data:
  redis:
  redis-config:
